### ISSUE TITLE
这插件需要什么设置么？无法直接用啊

### ISSUE THREAD

**Issue by loverto** [siteserver/sscms.form#1]
看插件的内容，里面有element-ui的元素，不需要编译么？

**Comment by starlying** [comment]
不需要编译，用的js打包版本，插件使用请参考一下帮助

**Comment by loverto** [comment]
我看了，照着用，页面不会显示表单，不知道哪里有问题，需要我提供什么信息么？

**Comment by loverto** [comment]
```
<!--在线留言-->
                    <div class="messageBox">
                        <stl:form name="在线留言" type="omsg"></stl:form>
                    </div>
```

**Comment by loverto** [comment]
![image](https://user-images.githubusercontent.com/3992018/95862663-ce751580-0d95-11eb-9f3e-19049f8550fe.png)
网页源码里都有这个了，还能用么？

还有在线预览的功能也无法使用

**Comment by wentan** [comment]
我也不能用，不知道要怎么使用

**Comment by loverto** [comment]
[加上这些内容](https://github.com/siteserver/cms/issues/2662)

**Comment by loverto** [comment]
https://github.com/siteserver/cms/issues/2662
